home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('skills/', views.skills, name='skills'),
    path('experiences/', views.experiences, name='experiences'),
    path('contact/', views.contact, name='contact'),
    path('schedule/', views.schedule, name='schedule'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.
class ScheduleModel(models.Model):
	name = models.CharField(max_length=50)

	DAY_CHOICES = ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')
	day = models.CharField(max_length=50, choices=DAY_CHOICES)

	date = models.DateField()
	time = models.TimeField()

	CATEGORY_CHOICES = ('task', 'Task'), ('quiz', 'Quiz'), ('other', 'Other')
	category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)

	location = models.CharField(max_length=50)

	def __str__(self):
		return self.name

home/forms.py
from django import forms
from .models import ScheduleModel

class scheduleForm(forms.ModelForm):

	class Meta:
		model = ScheduleModel
		fields = ('name', 'day', 'date', 'time', 'category','location')

story4/forms.py
from django import forms
class Message_Form(forms.Form):

    name = forms.CharField(label='Nama', required=False,
                           max_length=27, empty_value='Anonymous',
                           widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False,
                             widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs),
                              requires=True)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import scheduleForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def education(request):
    return render(request, 'education.html')

def skills(request):
    return render(request, 'skills.html')

def experiences(request):
    return render(request, 'experiences.html')

def contact(request):
    return render(request, 'contact.html')

def schedule(request):
	if request.method == "POST":
		form = scheduleForm(request.POST)
		if form.is_valid():
			form.save()
	form = scheduleForm()
	return render(request, 'form.html', {'form': form})

home/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>About</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>

    <h2 class="page-title">ABOUT</h2>
    
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p class="desc"> I am a second year Computer Science Student who loves to learn something new.</p>
            </div>
            <div class="col-md-4">
                <img src="{% static 'images/salsa.png' %}" class="rounded-circle">
            </div>
            <div class="col-md-4">
                <div id="profile">
                    <p class="profile-title">PROFILE</p>
                    <p>Name:</p>
                    <p class="indent">Salsabila Adnan</p>
                    <p>Date of Birth:</p>
                    <p class="indent">Jakarta, 11th January 2000</p>
                    <p>Gender:</p>
                    <p class="indent">Female</p>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
{% endblock %}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="bootstrap.min.js"></script>
    <link rel="stylesheet" type ="text/css" href=styles.css>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-static-top navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home:index' %}">Salsabila Adnan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'home:index' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'home:about' %}">About</a>
                <a class="nav-item nav-link" href="{% url 'home:education' %}">Education</a>
                <a class="nav-item nav-link" href="{% url 'home:skills' %}">Skills</a>
                <a class="nav-item nav-link" href="{% url 'home:experiences' %}">Experiences</a>
                <a class="nav-item nav-link" href="{% url 'home:contact' %}">Contact</a>
                <a class="nav-item nav-link" href="{% url 'home:schedule' %}">Schedule</a>
            </div>
        </div>
    </nav>
    
    {% block content %}
    {% endblock %}
</body>
</html>

home/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Contact</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>
    
    <h2 class="page-title">CONTACT</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <div class="row">
                    <img class="icon-email" src="{% static 'images/email.png' %}">
                    <p class="contact">salsabilaadnan11@gmail.com</p>
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
                    
    </div>

</body>
</html>
{% endblock %}

home/templates/education.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Education</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>
    
    <h2 class="page-title">EDUCATION</h2>

    <div class="container">
        <div class="page">
        <div class="timeline">
            <div class="timeline__group">
                <span class="timeline__year">2018-Now</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>Universitas Indonesia</p>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
                <span class="timeline__year">2015-2018</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>SMA Negeri 1 Depok</p>
                    </div>
                </div>
            <div class="timeline__group">
                <span class="timeline__year">2012-2015</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>SMP Negeri 2 Depok</p>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
                <span class="timeline__year">2006-2012</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>SD Yaspen Tugu Ibu 1 Depok</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    
</body>
</html>
{% endblock %}

home/templates/experiences.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Experiences</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>
    
    <h2 class="page-title">EXPERIENCES</h2>

    <div class="container">
        <div class="page">
        <div class="timeline">
            <div class="timeline__group">
                <span class="timeline__year">2019</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>Staff of Entrepreneurial Division DPM Fasilkom UI</p>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
                <span class="timeline__year">2019</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>Public Relations and Publications at Wisuda Genap Fasilkom UI</p>
                    </div>
                </div>
            <div class="timeline__group">
                <span class="timeline__year">2018-2019</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>Public Relations and Publications at Wisuda Ganjil Fasilkom UI</p>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
                <span class="timeline__year">2017</span>
                <div class="timeline__post">
                    <div class="timeline__content">
                        <p>Liaison Officer of Traditional Dance Competition at AKSI 40</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    
</body>
</html>
{% endblock %}

home/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Schedule</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>
    
    <h2 class="page-title">Schedule</h2>

    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
              <td>
               <table>
                <tr><td>{{ field.label }}</td></tr>
                <tr><td>{{ field }}</td></tr>
               </table>
              </td>
            {% endfor %}
            <br>
            <button type="submit">Add Schedule</button>
        </form>
    </div>


    
</body>
</html>
{% endblock %}

home/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Salsabila Adnan</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>
    <center>
        <h1 id="hello">HELLO,<br> I'M SALSA</h1>
        <div class="container">
            <div class="row">
                <div class="col-md">
                   <a id="menu-home" href="{% url 'home:about' %}">ABOUT</a>
                </div>
                <div class="col-md">
                   <a id="menu-home" href="{% url 'home:education' %}">EDUCATION</a>
                </div>
                <div class="col-md">
                   <a id="menu-home" href="{% url 'home:skills' %}">SKILLS</a>
                </div>
                <div class="col-md">
                   <a id="menu-home" href="{% url 'home:experiences' %}">EXPERIENCES</a>
                </div>
                <div class="col-md">
                   <a id="menu-home" href="{% url 'home:contact' %}">CONTACT</a>
                </div>
                <div class="col-md">
                   <a id="menu-home" href="{% url 'home:schedule' %}">SCHEDULE</a>
                </div>
            </div>
        </div>
    </center>    
        
</body>
</html>

home/templates/skills.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Skills</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'css/styles.css' %}">
</head>

<body>
    
    <h2 class="page-title">SKILLS</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p class="skillName">Microsoft Office</p>
                <img class="logo" src="{% static 'images/office.png' %}">
                <div class="skills ms"></div>                
            </div>
            <div class="col-md-4">
                <p class="skillName">Python</p>
                <img class="logo" src="{% static 'images/python.png' %}">
                <div class="skills python"></div>
            </div>
            <div class="col-md-4">
                <p class="skillName">Java</p>
                <img class="logo" src="{% static 'images/java.png' %}">
                <div class="skills java"></div>
            </div>
        </div>
    </div>

</body>
</html>
{% endblock %}